/**
 * ISO 3166-1 alpha-2 code to country name mapping
 */
const COUNTRY_NAMES: Record<string, string> = {
  AF: "Afghanistan",
  AL: "Albania",
  DZ: "Algeria",
  AO: "Angola",
  AR: "Argentina",
  AU: "Australia",
  AT: "Austria",
  BH: "Bahrain",
  BD: "Bangladesh",
  BE: "Belgium",
  BJ: "Benin",
  BW: "Botswana",
  BR: "Brazil",
  BF: "Burkina Faso",
  BI: "Burundi",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Republic of the Congo",
  CD: "DR Congo",
  CI: "Côte d'Ivoire",
  CZ: "Czech Republic",
  DK: "Denmark",
  DJ: "Djibouti",
  EG: "Egypt",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  ET: "Ethiopia",
  FI: "Finland",
  FR: "France",
  GA: "Gabon",
  GM: "Gambia",
  DE: "Germany",
  GH: "Ghana",
  GR: "Greece",
  GN: "Guinea",
  HU: "Hungary",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IE: "Ireland",
  IL: "Israel",
  IT: "Italy",
  JP: "Japan",
  JO: "Jordan",
  KE: "Kenya",
  KR: "South Korea",
  KW: "Kuwait",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  ML: "Mali",
  MR: "Mauritania",
  MU: "Mauritius",
  MX: "Mexico",
  MA: "Morocco",
  MZ: "Mozambique",
  NA: "Namibia",
  NE: "Niger",
  NG: "Nigeria",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PE: "Peru",
  PH: "Philippines",
  PL: "Poland",
  PT: "Portugal",
  QA: "Qatar",
  RO: "Romania",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SN: "Senegal",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SO: "Somalia",
  ZA: "South Africa",
  SS: "South Sudan",
  ES: "Spain",
  SD: "Sudan",
  SZ: "Eswatini",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syria",
  ST: "São Tomé and Príncipe",
  TZ: "Tanzania",
  TH: "Thailand",
  TG: "Togo",
  TN: "Tunisia",
  TR: "Turkey",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  VN: "Vietnam",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

/**
 * Get country name from ISO 3166-1 alpha-2 code.
 * Returns the code itself if not found.
 */
export const getCountryName = (code: string): string => {
  return COUNTRY_NAMES[code.toUpperCase()] || code;
};
